'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, CalendarDays, MapPin, Sparkles } from 'lucide-react'
import { AdSlot, SiteShell } from '@/components/site-shell'
import { calendarByDate, calendarEntries, disclaimer, ekadashis, festivals, festivalsByDate, formatDate, isSameMonth, monthLabel, muhurat, todayKey, type CalendarEntry } from '@/lib/observances'

const buttonClass = 'rounded-full border border-border px-3 py-2 text-sm font-medium transition hover:border-primary hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring'
function Header({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <div className="mx-auto max-w-6xl px-5 pb-8 pt-12 md:pt-16"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">Tithiii / {eyebrow}</p><h1 className="mt-4 max-w-3xl font-serif text-4xl leading-tight tracking-tight text-balance md:text-6xl">{title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">{intro}</p><div className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4 text-primary" /> Mumbai, India · IST</div></div> }
function Shell({ children, ...props }: { children: React.ReactNode; eyebrow: string; title: string; intro: string }) { return <SiteShell><Header {...props} /><main className="mx-auto max-w-6xl px-5 pb-16">{children}</main></SiteShell> }
function MonthControls({ date, setDate }: { date: Date; setDate: (date: Date) => void }) { return <div className="flex flex-wrap items-center gap-2"><button className={buttonClass} aria-label="Previous month" onClick={() => setDate(new Date(date.getFullYear(), date.getMonth() - 1, 1))}><ArrowLeft className="mr-1 inline size-4" /> Previous</button><span className="min-w-40 text-center font-serif text-xl">{monthLabel(date)}</span><button className={buttonClass} aria-label="Next month" onClick={() => setDate(new Date(date.getFullYear(), date.getMonth() + 1, 1))}>Next <ArrowRight className="ml-1 inline size-4" /></button><button className={buttonClass} onClick={() => setDate(new Date())}>Today</button></div> }
function Notice() { return <p className="mt-8 border-l-2 border-primary px-4 text-sm leading-6 text-muted-foreground">{disclaimer}</p> }

export function CalendarTool() { const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState(todayKey()); const days = useMemo(() => Array.from({ length: new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate() }, (_, i) => new Date(month.getFullYear(), month.getMonth(), i + 1)), [month]); const entry = calendarByDate[selected] as CalendarEntry | undefined; return <Shell eyebrow="calendar" title="Hindu calendar, with context" intro="Move through the month, select a date, and read the tithi, paksha, nakshatra and observance together."><AdSlot label="Advertisement" /><section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-border bg-card p-5"><MonthControls date={month} setDate={setMonth} /><div className="mt-6 grid grid-cols-7 gap-2 text-center text-xs text-muted-foreground">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <span key={day}>{day}</span>)}{Array.from({ length: new Date(month.getFullYear(), month.getMonth(), 1).getDay() }).map((_, i) => <span key={`blank-${i}`} />)}{days.map((day) => { const key = day.toISOString().slice(0, 10); const has = calendarByDate[key]; return <button key={key} onClick={() => setSelected(key)} aria-label={`Select ${formatDate(key)}`} className={`min-h-12 rounded-xl border p-2 text-sm ${selected === key ? 'border-primary bg-primary text-primary-foreground' : 'border-transparent hover:border-primary/50'} ${has ? 'font-semibold' : ''}`}>{day.getDate()}{has?.observance && <span className="mx-auto mt-1 block size-1 rounded-full bg-accent" />}</button> })}</div></div><div className="rounded-2xl bg-secondary p-6"><p className="text-sm text-muted-foreground">Selected date</p><h2 className="mt-2 font-serif text-2xl">{formatDate(selected)}</h2>{entry ? <div className="mt-6 grid gap-4 text-sm"><p><span className="text-muted-foreground">Tithi</span><br />{entry.tithi} · {entry.paksha}</p><p><span className="text-muted-foreground">Nakshatra</span><br />{entry.nakshatra}</p>{entry.observance && <p><span className="text-muted-foreground">Observance</span><br />{entry.observance}</p>}</div> : <p className="mt-6 leading-6 text-muted-foreground">No bundled observance is listed for this date. Open Panchang for a live daily calculation.</p>}<Link className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary" href={`/panchang?date=${selected}`}>Open daily Panchang <ArrowRight className="size-4" /></Link></div></section><Notice /></Shell> }

export function FestivalsTool() { const [month, setMonth] = useState(new Date()); const [category, setCategory] = useState('All'); const [selected, setSelected] = useState(festivals[0].date); const visible = festivals.filter((f) => isSameMonth(f.date, month) && (category === 'All' || f.category === category)); const selectedFestival = festivalsByDate[selected]; return <Shell eyebrow="festivals" title="Festivals worth planning for" intro="Browse upcoming observances by month and category, with a clear note about local practice."><section className="mt-4 flex flex-wrap items-center justify-between gap-4"><MonthControls date={month} setDate={setMonth} /><select className="rounded-full border border-border bg-background px-4 py-2 text-sm" value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filter festivals by category"><option>All</option><option>Festival</option><option>Jayanti</option><option>Regional</option></select></section><section className="mt-8 grid gap-6 lg:grid-cols-[1fr_.8fr]"> <div className="grid gap-3">{visible.length ? visible.map((festival) => <button key={festival.date} onClick={() => setSelected(festival.date)} className={`rounded-2xl border p-5 text-left transition hover:border-primary ${selected === festival.date ? 'border-primary bg-secondary' : 'border-border bg-card'}`}><p className="text-sm text-muted-foreground">{formatDate(festival.date)}</p><h2 className="mt-2 font-serif text-xl">{festival.name}</h2><p className="mt-2 text-sm text-muted-foreground">{festival.category} · {festival.note}</p></button>) : <div className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">No festivals match this month and category.</div>}</div><div className="rounded-2xl bg-secondary p-6">{selectedFestival ? <><p className="text-sm text-muted-foreground">Festival detail</p><h2 className="mt-2 font-serif text-2xl">{selectedFestival.name}</h2><p className="mt-4 leading-7 text-muted-foreground">{selectedFestival.note}</p><p className="mt-4 text-sm"><strong>Timing:</strong> {selectedFestival.timing}</p><Link className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary" href={`/calendar?date=${selectedFestival.date}`}>View in calendar <CalendarDays className="size-4" /></Link></> : <p className="text-muted-foreground">Choose a festival to see details.</p>}</div></section><Notice /></Shell> }

export function EkadashiTool() { const [month, setMonth] = useState(new Date()); const [selected, setSelected] = useState(ekadashis[1].date); const visible = ekadashis.filter((e) => isSameMonth(e.date, month)); const item = ekadashis.find((e) => e.date === selected); return <Shell eyebrow="ekadashi" title="Ekadashi, simply explained" intro="Browse the year’s Ekadashi dates and keep Dashami, Ekadashi and Parana details together."><section className="mt-4"><MonthControls date={month} setDate={setMonth} /></section><section className="mt-8 grid gap-6 lg:grid-cols-[1fr_.8fr]"><div className="grid gap-3">{visible.length ? visible.map((e) => <button key={e.date} onClick={() => setSelected(e.date)} className={`rounded-2xl border p-5 text-left ${selected === e.date ? 'border-primary bg-secondary' : 'border-border bg-card'}`}><p className="text-sm text-muted-foreground">{formatDate(e.date)}</p><h2 className="mt-2 font-serif text-xl">{e.name}</h2><p className="mt-2 text-sm text-muted-foreground">Tap to view fasting and Parana guidance.</p></button>) : <div className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">No bundled dates for this month.</div>}</div><div className="rounded-2xl bg-secondary p-6">{item ? <><Sparkles className="size-5 text-primary" /><h2 className="mt-3 font-serif text-2xl">{item.name}</h2><div className="mt-6 grid gap-4 text-sm"><p><span className="text-muted-foreground">Dashami</span><br />{item.dashami}</p><p><span className="text-muted-foreground">Ekadashi</span><br />{item.ekadashi}</p><p><span className="text-muted-foreground">Parana</span><br />{item.parana}</p></div><p className="mt-6 text-sm leading-6 text-muted-foreground">{item.note}</p></> : <p className="text-muted-foreground">Choose an Ekadashi to view details.</p>}</div></section><Notice /></Shell> }

export function MuhuratTool() { const [purpose, setPurpose] = useState<keyof typeof muhurat>('Marriage'); const [index, setIndex] = useState(0); const items = muhurat[purpose]; const item = items[index] ?? items[0]; return <Shell eyebrow="muhurat" title="Muhurat for meaningful moments" intro="Choose a purpose and browse the bundled time windows as a calm starting point for planning."><div className="mt-6 flex flex-wrap gap-2">{Object.keys(muhurat).map((key) => <button key={key} className={`${buttonClass} ${purpose === key ? 'border-primary bg-primary text-primary-foreground' : ''}`} onClick={() => { setPurpose(key as keyof typeof muhurat); setIndex(0) }}>{key}</button>)}</div><section className="mt-8 rounded-2xl border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Selected purpose</p><h2 className="mt-2 font-serif text-3xl">{item.title}</h2><p className="mt-2 text-muted-foreground">{formatDate(item.date)}</p></div><CalendarDays className="size-7 text-primary" /></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{item.windows.map((window) => <div className="rounded-xl bg-secondary p-4" key={window.label}><p className="text-sm text-muted-foreground">{window.label}</p><p className="mt-2 font-serif text-xl">{window.time}</p></div>)}</div></section><p className="mt-8 border-l-2 border-primary px-4 text-sm leading-6 text-muted-foreground">Muhurat timings are traditional, location-dependent information and are not guarantees or scientific predictions. Confirm important decisions with your own family or local practitioner.</p></Shell> }
