import type { Metadata } from 'next'
import { SiteShell, AdSlot } from '@/components/site-shell'
import { ArrowRight, CalendarDays, CircleHelp, Clock3, Mail, ShieldCheck } from 'lucide-react'
import { CalendarTool, EkadashiTool, FestivalsTool, MuhuratTool } from '@/components/panchang-tools'
const pages:Record<string,{title:string;intro:string;sections:{title:string;body:string}[]}>={
 calendar:{title:'Hindu Calendar',intro:'A clear monthly view of tithis, paksha, nakshatras and observances.',sections:[{title:'A calendar that respects context',body:'Hindu calendar dates can vary by location, sunrise and regional tradition. Tithiii presents the information alongside the city and timezone used for calculation so you can understand the context behind each date.'},{title:'What you can find here',body:'Browse daily Panchang details, festivals, Ekadashi, Purnima and Amavasya observances from one calm, easy-to-read calendar.'}]},
 festivals:{title:'Hindu Festivals',intro:'Important festival dates and the timings that help you plan mindfully.',sections:[{title:'Dates for your location',body:'Festival observances may follow different regional traditions. Always use the location selector and check the local practice that is meaningful to you.'},{title:'Information, not instruction',body:'Tithiii is an informational calendar. It does not make religious or scientific claims, and it does not replace guidance from your family, community or tradition.'}]},
 ekadashi:{title:'Ekadashi',intro:'Ekadashi dates, fasting windows and Parana timings, presented simply.',sections:[{title:'What is shown',body:'See the Ekadashi Tithi, the start and end of the fasting day, and Parana guidance when available for your city.'},{title:'A note on traditions',body:'Fasting practices vary. Please consider your health and follow the guidance of your own tradition or a trusted elder.'}]},
 purnima:{title:'Purnima',intro:'Full moon observances and dates in the Hindu calendar.',sections:[{title:'Full moon days',body:'Purnima marks the full moon Tithi. Its observance and associated festivals vary across regions and traditions.'}]},
 amavasya:{title:'Amavasya',intro:'New moon dates and associated calendar information.',sections:[{title:'New moon days',body:'Amavasya marks the new moon Tithi. Timings depend on location and the calculation method used.'}]},
 muhurat:{title:'Muhurat',intro:'A basic, respectful guide to auspicious time windows.',sections:[{title:'Use it as a starting point',body:'Muhurat information is traditionally interpreted through many factors, including location, purpose and family practice. Tithiii provides basic timing information only.'},{title:'Keep perspective',body:'These timings are cultural and traditional information, not scientific guarantees. For important decisions, use your own judgement and trusted guidance.'}]},
 about:{title:'About Tithiii',intro:'A calmer way to read the Hindu calendar.',sections:[{title:'Why we built it',body:'Tithiii makes daily Panchang information approachable without clutter, sensationalism or intrusive popups. We aim to be clear about the location, timezone and tradition behind every date.'}]},
 contact:{title:'Contact',intro:'Have a correction, question or suggestion?',sections:[{title:'Get in touch',body:'For feedback about the site or a possible data issue, email hello@tithiii.xyz. Please include the city, date and page you were viewing.'}]},
 privacy:{title:'Privacy Policy',intro:'Your privacy matters.',sections:[{title:'Information we use',body:'Tithiii may process the city you select to provide location-based timings. Browser location is never requested without your permission. We do not sell personal information.'}]},
 terms:{title:'Terms of Use',intro:'Please use Tithiii thoughtfully.',sections:[{title:'Informational service',body:'Tithiii provides calendar and Panchang information for general use. Data may contain errors or change as providers update their calculations. Use the site at your own discretion.'}]},
 disclaimer:{title:'Disclaimer',intro:'A clear note on accuracy and tradition.',sections:[{title:'Timings vary',body:'Panchang timings vary by location, timezone, sunrise and tradition. They should not be treated as scientific facts, guarantees or professional advice.'}]},
}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug]??pages.about;return {title:p.title,description:p.intro,alternates:{canonical:`/${slug}`}}}
export function ContentPage({slug}:{slug:string}){if(slug==='calendar')return <CalendarTool/>;if(slug==='festivals')return <FestivalsTool/>;if(slug==='ekadashi')return <EkadashiTool/>;if(slug==='muhurat')return <MuhuratTool/>;const p=pages[slug]??pages.about;return <SiteShell><main><div className="mx-auto max-w-4xl px-5 pb-16 pt-14 md:pt-20"><p className="text-xs font-semibold uppercase tracking-[.22em] text-primary">Tithiii / {slug}</p><h1 className="mt-4 max-w-3xl font-serif text-5xl leading-tight tracking-tight text-balance md:text-6xl">{p.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">{p.intro}</p><AdSlot label="Advertisement" slot="6459216650" /><div className="mt-12 grid gap-8">{p.sections.map(s=><section key={s.title} className="max-w-2xl"><h2 className="font-serif text-2xl">{s.title}</h2><p className="mt-3 text-base leading-8 text-muted-foreground">{s.body}</p></section>)}</div></div></main></SiteShell>}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return <ContentPage slug={slug}/>}
